language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aidario/client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aidario/client npm test

after_success:
  - docker build -t aidario/client ./client
  - docker build -t aidario/server ./server
  - docker build -t aidario/worker ./worker
  - docker build -t aidario/nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aidario/client
  - docker push aidario/server
  - docker push aidario/worker
  - docker push aidario/nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: complex
  env: Complex-env
  bucket_name: elasticbeanstalk-us-east-2-174879070563
  bucket_path: complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
